### PR TITLE
Expanded available methods for DataFrameFactors.

### PR DESCRIPTION
**Pull request by LTLA**
This allows us to treat `DataFrameFactor`s as `DataFrame`s. For example, doing something like `x$name` will return the same value as `unfactor(x)$name`, allowing us to use DFFs as memory-efficient drop-in replacements for DFs in many cases.

Ideally the `Factor()` constructor would handle proper construction, but I just couldn't figure out how to get:

```r
df <- DataFrame(X=sample(5, 100, replace=TRUE), Y=sample(c("A", "B"), 100, replace=TRUE))
dffac <- Factor(df)
dffac
## Factor object of length 100 with 0 metadata columns
## Levels: SimpleList object of length 2
```

to work - you can see how it just converts the `DFrame` to a `SimpleList`. It's still the former inside `.encode_as_Factor`, but once it enters `new()` it magically collapses to the latter. Not sure how this is happening.

Also ideally the `show` method would be more informative, maybe even giving the same kind of preview that `DataFrame` does.

### CODE REVIEW

**Comment by LTLA** [comment]
Returning to this - is it of interest?

**Comment by hpages** [comment]
Completely missed this sorry. Taking a look now.

**Comment by hpages** [comment]
One question is how far we want to go in making a DataFrameFactor object look and feel like a DataFrame given that these objects have some irreconcilable differences:
- The length of a DataFrameFactor is its number of rows, but the number of cols for a DataFrame.
- `x[i]` goes along the rows for DataFrameFactor, but along the columns for DataFrame.
- The names and metadata columns of a DataFrameFactor are along its rows (along the cols for a DataFrame).

So for example I find the fact that for a DataFrameFactor `x[i]` goes along the rows but `x[[i]]` goes along the columns _very_ confusing. It brings back bitter memories from the RangedData era!

At the very least we need to lower expectations and the documentation should make it clear that a DataFrameFactor will never be a drop-in replacement for DataFrame. Maybe the fundamental differences should be explained?

Also I think it will help that the `show()` method keeps the real nature of those objects very visible. 

Other than that, proposal looks ok I guess. Just some minor nitpicking about formatting:
- Tab instead of 4-spaces indent in DESCRIPTION
- No trailing spaces (`git diff` shows them in red to me and it hurts my eyes)
- No space between `function` and the opening parenthesis.
- I like to keep the order of things in NAMESPACE consistent with the order of things in `Collate:` so for example DataFrameFactor should go between DFrame and TransposedDataFrame in the exportClasses() section and between `## DataFrame-class.R:` and `## Pairs-class.R:` in the "Export non-generic functions" section.

Thanks

**Comment by LTLA** [comment]
Added a cautionary note about the limits of the mimicry to the docs. 

Also agree that the difference in `[[` and `[` behavior is pretty confusing so I just removed the `[[` method altogether. (Which reminds me: SEs also have bizarre `[[` behavior.)

Fixed all the formatting issues mentioned.

**Comment by hpages** [comment]
All good. Thanks!

**Pull request merged**
