### PR TITLE
Added combineRows, combineCols methods for DataFrames.

### PR DESCRIPTION
**Pull request by LTLA**
Pretty much as it says on the can.

```r
X <- DataFrame(x=1)
Y <- DataFrame(x=2, y="A")
Z <- DataFrame(z=TRUE)   
combineRows(X, Y, Z)
## DataFrame with 3 rows and 3 columns
##           x           y         z
##   <numeric> <character> <logical>
## 1         1          NA        NA
## 2         2           A        NA
## 3        NA          NA      TRUE

X <- DataFrame(x=1)
Y <- DataFrame(y=LETTERS[1:2])
Z <- DataFrame(z=TRUE)
rownames(X) <- "foo"
rownames(Y) <- c("foo", "bar")
rownames(Z) <- "bar"
combineCols(X, Y, Z)
## DataFrame with 2 rows and 3 columns
##             x           y         z
##     <numeric> <character> <logical>
## foo         1           A        NA
## bar        NA           B      TRUE
```

### CODE REVIEW

**Comment by LTLA** [comment]
So... good? Bad? Ugly?

**Comment by LTLA** [comment]
Also added a `combineUniqueCols()` function that is smart enough to do:

```r
X <- DataFrame(x=1)
Y <- DataFrame(y=LETTERS[1:2], dup=1:2)
Z <- DataFrame(z=TRUE, dup=2L)
rownames(X) <- "foo"
rownames(Y) <- c("foo", "bar")
rownames(Z) <- "bar"
combineUniqueCols(X, Y, Z)
## DataFrame with 2 rows and 4 columns
##             x           y       dup         z
##     <numeric> <character> <integer> <logical>
## foo         1           A         1        NA
## bar        NA           B         2      TRUE
```

Notice how we avoid getting duplicate copies of `dup` as these are collapsed into a single column. This doesn't quite respect the `combineCols()` contract, which is why I made a separate function to keep the two concepts separate.

This is helpful when merging `colData` in `combineRows,SummarizedExperiment-method`.

**Comment by LiNk-NY** [comment]
Any comments? Hervé @hpages or Michael @lawremi ?

**Comment by hpages** [comment]
Let me take a look at this

**Comment by hpages** [comment]
Focusing on `combineRows()` for now.

Unary form should work:
```
library(S4Vectors)
DF1 <- DataFrame(aa=1:3, aa=letters[1:3], bb=11:13, check.names=FALSE)
combineRows(DF1)
# Error in combineRows(DF1) : argument "y" is missing, with no default
```

This should work:
```
DF2 <- DataFrame(aa=201:202, bb=211:212, check.names=FALSE)
combineRows(DF1, DF2)
# Error in .format_mismatch_message(x_colnames, object_colnames) : 
#   the DataFrame objects to rbind do not have the same column names ('aa'
#   is unique)
```

There's also the question of whether `combineRows()` should work recursively i.e. if this works:
```
combineRows(DF2, make_zero_col_DFrame(2))
```
then it should also probably work when the DataFrame objects are nested:
```
x <- S4Vectors:::new_DataFrame(list(Z=DF2))
y <- S4Vectors:::new_DataFrame(list(Z=make_zero_col_DFrame(2)))
combineRows(x, y)
# Error in value[[3L]](cond) : 
#   failed to rbind column 'Z' across DataFrame objects:
#   the DataFrame objects to rbind do not have the same column names ('aa',
#   'bb' are unique)
```

Maybe it should also work on ordinary data.frames and when the data.frames are nested inside the DataFrames. Right now, this seems to work but it returns something wrong:
```
x <- S4Vectors:::new_DataFrame(list(Z=as.data.frame(DF2)))
y <- S4Vectors:::new_DataFrame(list(Z=as.data.frame(make_zero_col_DFrame(2))))
combineRows(x, y)
```
I'll work on this later today so you don't have anything to do for now.

**Comment by hpages** [comment]
Hi Aaron,

Sorry for the delay.

`combineRows()` is now in **S4Vectors** 0.29.11 and is used in the `rbind_mcols()` internal helper. I seized the opportunity to create a new unit (`R/DataFrame-combine.R` + associated man page and unit test file) where I've grouped all the combining methods for DataFrame objects. So now we need to add `combineCols()` and `combineUniqueCols()` to the new unit. Do you think you can rework your patch to take care of that?

About `combineUniqueCols()`:
```
library(S4Vectors)
X <- DataFrame(aa=1:4)
Y <- DataFrame(bb=11:14, aa=21:24, bb=31:34, check.names=FALSE)

combineUniqueCols(X, Y, use.names=FALSE)
# DataFrame with 4 rows and 2 columns
#           aa        bb
#   <integer> <integer>
# 1         1        11
# 2         2        12
# 3         3        13
# 4         4        14
# Warning message:
# In combineUniqueCols(X, Y, use.names = FALSE) :
#   column 'aa' is present in DataFrames 1 and 2 but contains different
#   values; only values from the former will be reported
```
Should probably also say something about the 2nd `bb` column disappearing.

Also what about providing a dedicated function for extracting the unique cols of a DataFrame object instead of `combineUniqueCols()`? Then people would just do something like `extractUniqueCols(combineCols(...))`.

Thanks,
H.

**Comment by LTLA** [comment]
> Do you think you can rework your patch to take care of that?

It is done.

> Should probably also say something about the 2nd `bb` column disappearing.

Tweaked the logic and warning appropriately.

> Also what about providing a dedicated function for extracting the unique cols of a DataFrame object instead of `combineUniqueCols()`? Then people would just do something like `extractUniqueCols(combineCols(...))`.

Depends on how nice you want the warning message to be when some columns disappear. Right now, I can give pretty informative messages about the index of the DF where the problem occurs. This wouldn't be possible if I split the functionality into a separate function - the output of `combineCols()` doesn't retain the provenance of each column.

**Comment by hpages** [comment]
Sorry for the delay. Looks good. Only 3 minor cosmetic things:

- In the NAMESPACE:
    ```
    ## combine-methods.R:
    combineUniqueCols
    ```
  This function is defined in `DataFrame-combine.R`.

- The use of the word "breaks" in this comment:

  > This breaks the combineCols contract ...

  This caught my attention but it's actually misleading because there's no expectation that `combineUniqueCols()` would have to follow the `combineCols()` contract. So maybe something along the line of:

  > Unlike with combineCols(), the ncol() of combineUniqueCols's output is not equal to the sum of the
  > ncols() of its inputs.

  would avoid a false alert.

- Can you specify the requirements for `combineUniqueCols()` to work? I see that it's currently implemented as a regular function and not a generic like `combineRows()` or `combineCols()`. This seems to make sense because it looks like you've implemented it as a wrapper around `combineCols()` so I guess the idea is that it's expected to work on any inputs for which `combineCols()` works. Is that correct? What would happen for example if some rectangular objects in the inputs don't have colnames (e.g. SummarizedExperiment object with no colnames)? Would it still work? If not, would it fail gracefully? Please add a one-liner comment above `combineCols()` definition that says something like:

  > Will work on any rectangular objects for which 'combineCols()' works.

  or

  > Will work on any rectangular objects that have colnames and for which 'combineCols()' works.

  or something like that. Also clarify the requirements in the man page.

BTW I've changed my mind and I'm not sure I still like to have the `combineRows()` and `combineCols()` generics defined in **BiocGenerics** anymore so now I'm considering moving them to **S4Vectors**. But let's get this PR merged first and I'll move the generics later.

Thanks

**Comment by LTLA** [comment]
Done.

**Comment by hpages** [comment]
So what happens in case `combineUniqueCols`'s input doesn't have `colnames`? Seems to be silently ignored:
```
library(SummarizedExperiment)

setMethod("combineCols", "SummarizedExperiment", function(x, y, ..., use.names=TRUE) cbind(x,y,...))

se <- SummarizedExperiment(matrix(1:12, ncol=3))

colnames(se)
# NULL
combineCols(se, se)
# class: SummarizedExperiment 
# dim: 4 6 
# metadata(0):
# assays(1): ''
# rownames: NULL
# rowData names(0):
# colnames: NULL
# colData names(0):

combineUniqueCols(se, se)
# class: SummarizedExperiment 
# dim: 4 0 
# metadata(0):
# assays(1): ''
# rownames: NULL
# rowData names(0):
# colnames: NULL
# colData names(0):
```
Is that what we want?

Also `combineUniqueCols()` assumes that the specific `combineCols()` method that it calls supports the `use.names` arg. What will happen if it doesn't? Maye we should add the `use.names` arg to the generic.

**Comment by LTLA** [comment]
> Is that what we want?

After some thought, I decided to just fall back to returning `combineCols()` when the columns are not named. This is probably user-friendly than spitting out an error and allows `combineUniqueCols()` to be used wherever `combineCols()` is useable.

> Maye we should add the `use.names` arg to the generic.

Yes, that would be nice.

**Comment by hpages** [comment]
What if some objects have colnames and others don't?
```
library(S4Vectors)
setMethod("combineCols", "matrix", function(x, y, ..., use.names=TRUE) cbind(x, y, ...))
m1 <- m2 <- matrix(1:12, ncol=3)
colnames(m2) <- LETTERS[1:3]
combineUniqueCols(m1, m2)
#        A B  C
# [1,] 1 1 5  9
# [2,] 2 2 6 10
# [3,] 3 3 7 11
# [4,] 4 4 8 12
```

Make sure to use the 2D API, and not the data.frame API for extracting columns:
```
combineUniqueCols(m2, m2)
# Error in combined[[d]] : subscript out of bounds
```

Unary version needs to work:
```
combineUniqueCols(m1)
# Error in combineCols(x, y, ..., use.names = use.names) : 
#   argument "y" is missing, with no default
```

Finally some `combineCols()` and `combineUniqueCols()` examples in the man page would be nice.

Almost there. Thanks!

**Comment by LTLA** [comment]
Decided to not attempt any deduplication when any DF has no colnames, given that empty colnames don't have an obvious interpretation here; probably unwise to treat them as duplicates in an unnamed 2D object. So:

```r
library(S4Vectors)
setMethod("combineCols", "matrix", function(x, y, ..., use.names=TRUE) cbind(x, y, ...))
m1 <- m2 <- matrix(1:12, ncol=3)
colnames(m2) <- LETTERS[1:3]
combineUniqueCols(m1, m2)
##             A B  C
## [1,] 1 5  9 1 5  9
## [2,] 2 6 10 2 6 10
## [3,] 3 7 11 3 7 11
## [4,] 4 8 12 4 8 12
```

**Comment by hpages** [comment]
Strange decision. Why not declare that `combineUniqueCols()` expects that all the input objects have colnames and gracefully fail if any of them doesn't?

```
> combineUniqueCols(m1, m2, m1, m2)
            A B  C        A B  C
[1,] 1 5  9 1 5  9 1 5  9 1 5  9
[2,] 2 6 10 2 6 10 2 6 10 2 6 10
[3,] 3 7 11 3 7 11 3 7 11 3 7 11
[4,] 4 8 12 4 8 12 4 8 12 4 8 12
```

If I call something like `combineUniqueCols()`, I really expect the output to have unique colnames. This is the only reason I would call that instead of something like `combineCols()` or `cbind()`.

**Comment by LTLA** [comment]
The idea was to ensure that `combineUniqueCols()` works in all circumstances where `combineCols()` works. If I'm writing a function that calls `combineCols()`, this guarantee means that I should be able to swap it for `combineUniqueCols()` without the need for further inspection of the arguments to see whether they have column names.

Whether or not the current behavior is expected is another question. I don't have any use cases involving unnamed inputs, so I can't really say what would be the right behavior here. Perhaps we could only consider non-`""` names for deduplication, which would be as simple as adding a `setdiff(dupped, "")` somewhere. 

But regardless, a warning and _some_ kind of return value would be preferable to an error, given that the intent of the `combine*` functions is to be more generous than `cbind`.

**Comment by hpages** [comment]
Being generous or flexible is not the same as trying to return something at all costs, even when it doesn't make sense. Anyways, time to move on.

Only thing left is support for unary form:
```
> combineUniqueCols(m1)
Error in .local(x, y, ...) : argument "y" is missing, with no default
```

**Comment by LTLA** [comment]
I switched to what I mentioned above, given that the documentation states that the column names must be unique.

```r
library(S4Vectors)
setMethod("combineCols", "matrix", function(x, y, ..., use.names=TRUE) cbind(x, y, ...))
m1 <- m2 <- matrix(1:12, ncol=3)
colnames(m2) <- LETTERS[1:3]
combineUniqueCols(m1, m2, m1, m2)
##             A B  C
## [1,] 1 5  9 1 5  9 1 5  9
## [2,] 2 6 10 2 6 10 2 6 10
## [3,] 3 7 11 3 7 11 3 7 11
## [4,] 4 8 12 4 8 12 4 8 12
```

The special casing of unnamed columns seems to be acceptable; after all, they are a special case.

The unary method for DFs should work fine, there just isn't a `matrix,ANY` method in your example. For example:

```r
library(S4Vectors)
df <- DataFrame(X=1, row.names="A")
combineUniqueCols(df)
## DataFrame with 1 row and 1 column
##           X
##   <numeric>
## A         1
```

**Comment by hpages** [comment]
> The unary method for DFs should work fine

oh I see. Perfect, thanks!

**Comment by hpages** [comment]
> Maybe we should add the use.names arg to the generic.

Done in **S4Vectors** 0.29.16.

Also the `combineRows()` and `combineCols()` generics are now in **S4Vectors** instead of **BiocGenerics** (both are documented in the man page for RectangularData objects).

**Pull request merged**
