### PR TITLE
More informative errors from rbinding DataFrames

### PR DESCRIPTION
**Pull request by LTLA**
```r
library(S4Vectors)
A <- DataFrame(A=10)
B <- DataFrame(B=10)
rbind(A, B)
## Error in map_x_colnames_to_object_colnames(colnames(object)) : 
##   the DataFrame objects to rbind have mismatching colnames ('A', 'B')
```

```r
library(S4Vectors)
A <- DataFrame(A=I(matrix(10)))
B <- DataFrame(A=I(cbind(1,2)))
rbind(A, B)
## Error in value[[3L]](cond) : failed to rbind 'A' across DataFrames
##   number of columns of matrices must match (see arg 2)
```

... which at least gives the user some indication of what went wrong.

### CODE REVIEW

**Comment by hpages** [comment]
With this patch I get:
```
library(IRanges)
A <- DataFrame(A=10, B=8, B=12, check.names=FALSE)
B <- DataFrame(A=10, A=8, B=12, check.names=FALSE)
rbind(A, B)
# Error in map_x_colnames_to_object_colnames(colnames(object)) : 
#   the DataFrame objects to rbind have mismatching colnames ()
```

**Comment by LTLA** [comment]
Latest patch now does:

```r
library(S4Vectors)
A <- DataFrame(A=10, B=8, B=12, check.names=FALSE)
B <- DataFrame(A=10, A=8, B=12, check.names=FALSE)
rbind(A, B)
## Error in map_x_colnames_to_object_colnames(colnames(object)) : 
##   the DataFrame objects to rbind have mismatching colnames ('B', 'A')
```

I also took the liberty of extending this to the previous error message:

```r
library(S4Vectors)
A <- DataFrame(A=10, B=12, check.names=FALSE)
B <- DataFrame(A=10, check.names=FALSE)
rbind(A, B)
## Error in map_x_colnames_to_object_colnames(colnames(object)) : 
##   the DataFrame objects to rbind have different numbers of columns (e.g. 
##   'B')
```

Incidentally, this causes a segfault on my machine at `selectHits`:

```r
library(S4Vectors)
A <- DataFrame(A=10, B=8, B=12, check.names=FALSE)
B <- DataFrame(A=10, A=8, B=12, check.names=FALSE)
rbind(B, A)
```

**Comment by hpages** [comment]
ouch, not good! Looking into this...

**Comment by hpages** [comment]
Should be fixed in S4Vectors 0.25.2. Can you test your patch against this? Will port to release. Thx!

**Comment by LTLA** [comment]
All green on my end.

**Comment by hpages** [comment]
Listing column names in the error message is not really useful or relevant here:
```
x <- DataFrame(A=11, B=12, check.names=FALSE)
y <- DataFrame(C=21, D=22, E=23, check.names=FALSE)
rbind(x, y)
# Error in map_x_colnames_to_object_colnames(colnames(object)) : 
#   the DataFrame objects to rbind have different numbers of columns (e.g.
#   'A', 'B', 'C', ...)
```

Given that `rbind(x, y)` knows how to realign the columns in `y` based on their name, something like this is allowed:
```
x <- DataFrame(A=11, B=12, C=13, A=14, check.names=FALSE)
y <- DataFrame(C=21, A=22, A=23, B=24, check.names=FALSE)
rbind(x, y)
# DataFrame with 2 rows and 4 columns
#           A         B         C         A
#   <numeric> <numeric> <numeric> <numeric>
# 1        11        12        13        14
# 2        22        24        21        23
```
But something like this is not because the columns in `y` cannot be realigned:
```
y <- DataFrame(C=21, B=22, B=23, A=24, check.names=FALSE)
rbind(x, y)
# Error in map_x_colnames_to_object_colnames(colnames(object)) : 
#   the DataFrame objects to rbind have mismatching colnames ('A', 'B')
```
In that case I'm not sure that the error message above is a lot more informative than the old one.

The meaning of "must have the same colnames" in the old error message was "must have the same set of columns (based on the names) possibly in different order (and if a column name is repeated in one of the 2 objects to bind then it must be repeated the same number of times in the other object to bind)".

**Comment by LTLA** [comment]
The motivation was to give some better error messages when dealing with DataFrames that are deeply nested within other objects. For example, the SCE class has the following:

`SingleCellExperiment` (SE subclass)
- `int_colData` (an internal DF parallel to SE columns)
   - `reducedDims` (another internal DF nested in `int_colData`)

If people try to combine two SCEs with differences in the numbers of `reducedDims`, they would previously get a cryptic error about mismatching DFs. This patch would provide a more useful message referring to the different identities of the reduced dimensions (e.g., "PCA", "TSNE"), which gives people a better idea of what has gone wrong.

**Comment by hpages** [comment]
Just tell me what you want to do. I'm not against better error messages, all the contrary. Was just showing some specific situations where the patch produces a slightly confusing message rather than a more informative one. So some fine tuning is needed.

**Comment by LTLA** [comment]
Perhaps it might be less confusing if we split it by argument, e.g., 

```
Error in map_x_colnames_to_object_colnames(colnames(object)) : 
  the DataFrame objects to rbind have mismatching colnames ('A'
  vs 'B')
```

... which is not too bad, because those are the mismatching colnames. I guess I'm not so much worried about the situation where you have duplicated colnames within a DF, that seems like a pretty difficult situation already.

**Comment by hpages** [comment]
I'm fine with that. Just let me know when you have something that is ready for me to look at again.

**Comment by LTLA** [comment]
```r
library(S4Vectors)
A <- DataFrame(A=10, B=8, B=12, check.names=FALSE)
B <- DataFrame(A=10, A=8, B=12, check.names=FALSE)
rbind(A, B)
## Error in map_x_colnames_to_object_colnames(colnames(object)) :
##  the DataFrame objects to rbind have mismatching colnames ('B' vs 'A')

A <- DataFrame(A=10, B=12, check.names=FALSE)
B <- DataFrame(A=10, check.names=FALSE)
rbind(A, B)
## Error in map_x_colnames_to_object_colnames(colnames(object)) :
##   the DataFrame objects to rbind have different numbers of columns ('B'
##   is unique)
```

And with added grammar:

```r
A <- DataFrame(A=10, B=12, C=10, check.names=FALSE)
B <- DataFrame(A=10, check.names=FALSE)
rbind(B, A)
## Error in map_x_colnames_to_object_colnames(colnames(object)) :
##   the DataFrame objects to rbind have different numbers of columns ('B',
##   'C' are unique)
```

**Comment by hpages** [comment]
Looks good, thanks!

2 minor things

1. I still find this confusing:
```
x <- DataFrame(as.list(setNames(1:26, letters)), check.names=FALSE)
y <- DataFrame(as.list(setNames(1:26, LETTERS)), check.names=FALSE)
rbind(x, y[-26])
# Error in map_x_colnames_to_object_colnames(colnames(object)) : 
#   the DataFrame objects to rbind have different numbers of columns ('a',
#   'b', 'c', ... vs 'A', 'B', 'C', ...)
```
We're telling the user that there is something wrong about the **number** of columns, but then we show column **names**. I think that either "number of" should be removed from the message or what's in the parenthesis should be "(26 vs 25)".

2. Maybe add "column" and a colon here:
```
rbind(A, B)
# Error in value[[3L]](cond) : failed to rbind 'A' across DataFrames
#   number of columns of matrices must match (see arg 2)
```
so would be "failed to rbind **column** 'A' across DataFrames:"

Don't bother the unit tests. I'm not a big fan of unit testing the content of error messages. (We still need to improve the unit tests with more exotic `rbind()` operations though, as the recent segfault demonstrated, but that's on me.)

**Comment by LTLA** [comment]
Right.

```r
library(S4Vectors)
A <- DataFrame(A=10, B=8, B=12, check.names=FALSE)
B <- DataFrame(A=10, A=8, B=12, check.names=FALSE)
rbind(A, B)
## Error in .format_mismatch_message(x_colnames, object_colnames) :
##   the DataFrame objects to rbind do not have identical column names ('B'
##   vs 'A')

A <- DataFrame(A=10, B=12, check.names=FALSE)
B <- DataFrame(A=10, check.names=FALSE)
rbind(A, B)
## Error in .format_mismatch_message(x_colnames, object_colnames) :
##  the DataFrame objects to rbind do not have identical column names ('B'
##   is unique)

x <- DataFrame(as.list(setNames(1:26, letters)), check.names=FALSE)
y <- DataFrame(as.list(setNames(1:26, LETTERS)), check.names=FALSE)
rbind(x, y[-26])
## Error in .format_mismatch_message(x_colnames, object_colnames) :
##   the DataFrame objects to rbind do not have identical column names ('a',
##   'b', 'c', ... vs 'A', 'B', 'C', ...)

A <- DataFrame(A=I(matrix(10)))
B <- DataFrame(A=I(cbind(1,2)))
rbind(A, B)
## Error in value[[3L]](cond) :
##   failed to rbind column 'A' across DataFrames:
##   number of columns of matrices must match (see arg 2)
```

Regardless of whether it's the number or identity of the column names that are mismatched, everyone now gets the same error. I focused on the column names because it's more helpful than the numbers.

**Comment by hpages** [comment]
Makes sense. Thanks for the PR.

(I just replaced "identical" with "same" because I find the former too connoted: it can mislead the user into thinking that `rbind(x, y)` expects identical colnames as in `identical(colnames(x), colnames(y))`, which is not the case.)

**Comment by LTLA** [comment]
Thanks. Now I can do this (tagging @LuyiTian):

```r
sce1 <- mockSCE()
reducedDim(sce1, "PCA") <- matrix(runif(10000), nrow=ncol(sce1))
sce2 <- mockSCE()
reducedDim(sce2, "PCA") <- matrix(runif(5000), nrow=ncol(sce2))
cbind(sce1, sce2)
## Error in value[[3L]](cond) : 
##   failed to combine 'int_colData' in 'cbind(<SingleCellExperiment>)'
## failed to rbind column 'reducedDims' across DataFrames:
##   failed to rbind column 'PCA' across DataFrames:
##   number of columns of matrices must match (see arg 2)
```

**Pull request merged**
