### PR TITLE
Avoid unfactor'ing in Factor comparisons

### PR DESCRIPTION
**Pull request by LTLA**
This should provide a modest efficiency improvement for large Factors with few levels.

### CODE REVIEW

**Comment by LTLA** [comment]
The latest commit fixes the following behavior:

```r
library(S4Vectors)
example(Factor)
is.unsorted(unfactor(sort(F2)))
## TRUE
```

**Comment by hpages** [comment]
Looks good but what about small Factors with many levels? Aren't they going to be slowed down by this? It sounds like the code could have 2 branches like in the `as.character()` method for Factors so nobody gets penalized.

**Comment by LTLA** [comment]
It's done, but the code got a whole lot uglier. Couldn't figure out how to avoid the redundancy as `callNextMethod()` needs to lie within a method definition.

**Comment by hpages** [comment]
I think you want `callGeneric()` instead of `callNextMethod()` here. `callNextMethod()` searches for the "closest parent method" starting from the class used in the **signature** of the method from which it is called, NOT from `class(x)`. Note that using `callGeneric()` means that the method will call itself if the result of unfactoring is again a Factor (possible in theory). However subsequent unfactorings will eventually return a Vector that is not a Factor so infinite recursion is avoided.

**Comment by LTLA** [comment]
Right. Well, in any case, I just refactored it to avoid repeating the same code for `pcompare` and `match`. This doesn't use any `call*()` stuff at all because the new internal function is not a method.

**Comment by hpages** [comment]
Excellent. Thanks for the PR!

**Pull request merged**
