### PR TITLE
Deals sanely with NAs in DataFrames during comparisons

### LINKED ISSUE #49: selfmatch for DataFrame fails badly with NAs inside
```r
ids <- c(1:10, 1:10)
extra <- c(10:1, 10:1)
ids[1] <- NA
extra[2] <- NA

library(S4Vectors)
a <- DataFrame(ids, extra)
selfmatch(a)
##  [1]  1  1  1  1  1  1  1  1  1  1 11 12  1  1  1  1  1  1  1  1
```

Well, that just can't be right.

Some digging indicates that `xtfrm` is freaking out because `sameAsPreviousROW()` is spitting out `NA`s. We should probably add specialized `sameAsPreviousROW()` methods for all the primitive data types that could contain `NA`s, and handle any `NA`s therein more gracefully. 

- A comparison to a `NA` and non-`NA` value should yield `FALSE` rather than `NA`, for the purposes of this function.
- A comparison between two `NA` values... not sure what should happen here. I guess it would also be `FALSE`, as two missing values are not equal, but `match()` seems to disagree (e.g., `match(NA, NA)`). Alternatively, this could emit `NA`, but we'd have to go through and secure all uses of `sameAsPreviousROW()` to handle such instances.

<details>
<summary>Session info</summary>

```
R version 3.6.0 Patched (2019-05-10 r76483)
Platform: x86_64-apple-darwin17.7.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /Users/luna/Software/R/R-3-6-branch-dev/lib/libRblas.dylib
LAPACK: /Users/luna/Software/R/R-3-6-branch-dev/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
[1] S4Vectors_0.23.19   BiocGenerics_0.31.5

loaded via a namespace (and not attached):
[1] compiler_3.6.0
```
</details>

### PR DESCRIPTION
**Pull request by LTLA**
Fixes #49.

### CODE REVIEW

**Comment by lawremi** [comment]
Thanks. It should be possible to share more code between the default and numeric methods. You could use the "atomic" class defined by IRanges to catch all the atomic vectors (you're missing complex right now), but note that raw vectors do not support `NA`. Rle's can also contain `NA`s; are those handled?

**Comment by LTLA** [comment]
Done, except for `atomic`, because that would introduce a circular dependency.

**Comment by lawremi** [comment]
Not sure what you mean by a circular dependency. It would let you define fewer methods. Btw, the `cumsum(runLength(x))` could be `end(x)`.

**Comment by LTLA** [comment]
Well, if `atomic` is defined by IRanges, I'd have to Depend or Import IRanges in S4Vectors to define a method for that class. But IRanges itself Depends on S4Vectors.

**Comment by hpages** [comment]
We should move the atomic class to S4Vectors. I'll do it today.

**Comment by hpages** [comment]
Done (commit b0bd7c8f65251c3cdb329078703bf3af0b2a1e54).

**Comment by LTLA** [comment]
Looks like `sameAsPreviousROW,integer-method` is derived from the `numeric-method` rather than the `atomic-method`. Slightly inefficient with an unnecessary `is.nan()` check... oh well.

**Comment by LTLA** [comment]
Nudge.

**Comment by lawremi** [comment]
I guess `setMethod("sameAsPreviousROW", "integer", .atomic_sameAsPreviousROW)` would be a simple workaround?

**Comment by hpages** [comment]
@lawremi Can you take a look at this unit test failure? https://bioconductor.org/checkResults/3.10/bioc-LATEST/S4Vectors/malbec1-checksrc.html
It prevents the `atomic` move and other important recent changes to S4Vectors from propagating. Thanks!
H.

**Comment by lawremi** [comment]
Just for the record, the bug should be fixed as of a couple days ago. This PR looks good from my end.

**Comment by hpages** [comment]
@lawremi Thx!

**Pull request merged**
